language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: 180a6bf7-33ab-48f8-a503-31a3fe37d131
  app: frozen-meadow-96290
  on:
    repo: AlexMcComb/peek-api
