language: node_js
node_js: node
services:
  - mongodb

deploy:
  provider: heroku
  api_key:
    secure: NW3dmZUUip0PeMpOAqUSK9zBNyuHYscIGfZvY4QnBMIemST05tuB/kXKrFkifcLZ2L1TnRTHV4o/DQmtXXNyin4SwK/bvtPCfDX6BfQTgd/4kOA0kutzmnJPUBvV6Z4ArIG7L53LIgq/XJp1IH5Kv1cWihRDI/3gT2VyjO8D44z+l8gcqfQpuzKyCcdmTF8fqZcy7Tb3udv8l9qAaWfY7KtHt34qWClO7IOqiBJcgJxl0FJe/p0NTXZG6SEQY7cWmkeS7ILY9+LC1e2fAId8rSiiWnLv2CqUQkLdQKH9rkmMGq9Biv/XhN2I0oNncyr0qydcTYsk3M56wkYM1BEL8uaGLvhFv9lMoDVdmABFyo/edtEXdvtfJZp3mKT753lJXyWPk1gWkRuVnB596FULx4c78+kuwt0/64Cn0qz+NpAHjoSCkr9RHfVS0wlGqSBOf2+4TU/dRcOF3e6Q6zR91jdB/wOH5owtMR8rroESU1NCd5HrbBW2J6mneowISmcv705QHcK7EbWx2PMXMd6/MyPoNbRzuhTJpILbsaFeqP87J5xS4bG77gomQkFe2CZ0zYU0S+/gYJjzeRi8KChwK1gdCxSCR6VPkZLSosGvxCst58ACXgcLvDno+sOjftElQ9YhM7RYN4CRjOmRnpCPdYk3v5OJ7KlNYv3XerFK/uM=
  app: whispering-wave-49810
  on:
    repo: AlexMcComb/peek-api
