language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: IcsW+75dIrhuuAH0Qk//H1CKffa8gVXLSRBUo5m0KMbeH3qEfjlNCgvhuduZfx9R4iS59FGEgvLWfLPFAYC5erJ2lxs8yu+CYEoEL1CT/zrMza6omiIqquQbOLyZlU86v2CXOYwx5npUE/gNAJVWZpdr43q+B/9g5DNYsxMIxL0dLfjn7Zp/9Px1xMA7XBkYQFV5wm5UIlFTs1Mf2/qac/nV8Lk02PWDBBP+jI6P+dnTIqtUtJKoeGAn0BcaNNGfspDEC5QgxZLIjHlwvsGVDQMLl6Gt86E3VNL8D5ui3Sa33mbgL1kVJuDm5kqFsscBkZ4bFFTBq46h5H37t5aE7ctBd8VnCeYJxtQm2UBaUHcbtMxyTk4q0rn0RqkYzPi9skGw15S4KhLH3VVZMgzWNBJegeF/jjkPzeQ6/YOsZUWhA8YtpwkMgKA6qEb4HnIPfI/EoErRGBDNMke6orBpEovRsDC/+vLtD929FzstxR4zL7JwkhoW2jgnTLpvDYZgW18A7AbPIoWSPlbp/CsSD3zHRViVukw/H0PQAGVBvbB0SX7AeX8gJQb1yDsUkLWVYlYq7usNzEU/soY0I+mlAqk7uo2T6RiEfHp7YSU8Kp/5kFmi7dfuHXQKDMqLEB2mVvcopN0vXqHUPv2pSg9voZYvK3+uPqfivUji6vfg1Ts=
  app: frozen-meadow-96290
  on:
    repo: AlexMcComb/peek-api
