language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: Kf4GGhcYHMEHvWKJyxltN0xGxmVPNH5E1w8XMVuwKvcEAjlHc/ocB1hHXyKpx4Ga6QWXQheuZ1FEOglYqCgQCTJX2RC6GLUIavaOJ5YLpjgwmaE8yWbRC1xR+w5CufwKcWHIadcz8piqEgKgCgn9s2u2bg8cWxCcfMM0cy57NXB4R9OlqU4XAJ0Q/v3QE1qm/BEAyf+HOKu//d7+T+yEOxhRVahOwd8KyP7uAgI1q23ir9XMApdIifdnhNc/vr7GCNMQpvW05Pvhf2yv09+dONG6RsWEGJoEug2r7N+iBtJoic8j8jn7j8cxViTv8z9KWpESWAXs+F6okperMFcJ13CthzlP0iMKX7waSY1QNfKDDrjaSAJ7XtCQM6NaLfwS3dFrDr65zZayqlAelPiJG0UKSjUO/WDL/Ue53pGtSXVKuehAlmXq+sjC2y7Y81L9r0f57JDX4LSgMYxgbJPFrmnMWXYrV30SFZnZRYIhQJqSsWLwHjmmXBum59NVKtrcvKrpmFM4qlKd6t8g1LJP/mEN56P370wCzemk6U3rADL1xDSF0srOF33qX2qitiiASuPnHyrJvuJOHlItVpaT6osv8+EDAKef0jpMFSuKozotzggmxZ8fTIwLTcOZEXpEELbBx7pdx7moboG2I7DMlEcBSjW5DGX8sOXhXwjT6q8=
  app: blooming-springs-68945
  on:
    repo: AlexMcComb/peek-api
